version: "3.8"

services:
  backend:
    build: ./go-todo
    ports:
      - "8080:8080"
    # environment:
    #   - DATABASE_URL=/app/todos.db
    # volumes:
    #   - ./go-todo:/app # Mount source code
    # depends_on:
    #   - db
    # command: bash
